(delete 'width initial-frame-alist)
(delete 'height initial-frame-alist)
(delete 'top initial-frame-alist)
(delete 'left initial-frame-alist)
(setq initial-frame-alist (append (list
'(width . 233)
'(height . 68)
'(top . 22)
'(left . 8))
initial-frame-alist))
